/**
 * ═══════════════════════════════════════════════════════════════
 * AI Trade Decision Support Dashboard — Frontend Script
 * ═══════════════════════════════════════════════════════════════
 *
 * This script powers the web dashboard:
 *   1. Loads prediction.json (generated by predict.py)
 *   2. Renders candlestick / line charts with SMA/EMA overlays
 *   3. Displays the AI prediction prominently
 *   4. Handles behavioral emotion logging (stored in localStorage)
 *   5. Shows emotion summary table with distribution bars
 *
 * Dependencies: Plotly.js (loaded in index.html)
 */

// ──────────────────────────────────────────────────────────
// GLOBAL STATE
// ──────────────────────────────────────────────────────────
let predictionData = null;       // Loaded from prediction.json
let currentChartType = 'candlestick';  // 'candlestick' or 'line'
let selectedEmotion = null;      // Currently selected emotion button

// localStorage key for emotion entries
const EMOTION_STORAGE_KEY = 'trade_emotion_log';


// ──────────────────────────────────────────────────────────
// INITIALIZATION — runs when DOM is fully loaded
// ──────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
    loadPredictionData();
    setupChartToggle();
    setupEmotionButtons();
    setupSaveButton();
    loadAndDisplayEmotionSummary();
});


// ══════════════════════════════════════════════════════════
// 1. LOAD PREDICTION DATA FROM JSON
// ══════════════════════════════════════════════════════════
async function loadPredictionData() {
    try {
        const response = await fetch('data/prediction.json');
        if (!response.ok) throw new Error(`HTTP ${response.status}`);

        predictionData = await response.json();
        console.log('✅ Prediction data loaded:', predictionData.prediction);

        // Update all dashboard components
        updatePredictionCard();
        updateMetricsBar();
        updateLastUpdated();
        renderChart();

    } catch (error) {
        console.error('❌ Failed to load prediction.json:', error);
        document.getElementById('prediction-display').textContent = 'ERROR';
        document.getElementById('status-badge').innerHTML =
            '<span class="status-dot" style="background:var(--down-color)"></span><span>Data Error</span>';
    }
}


// ══════════════════════════════════════════════════════════
// 2. UPDATE THE AI PREDICTION CARD
// ══════════════════════════════════════════════════════════
function updatePredictionCard() {
    if (!predictionData) return;

    const display = document.getElementById('prediction-display');
    const card = document.getElementById('prediction-card');
    const confidenceEl = document.getElementById('prediction-confidence');
    const accuracyEl = document.getElementById('model-accuracy');
    const barEl = document.getElementById('confidence-bar');

    const isUp = predictionData.prediction === 'UP';
    const direction = isUp ? 'up' : 'down';

    // Set prediction text with arrow
    display.textContent = isUp ? 'UP ▲' : 'DOWN ▼';
    display.className = `prediction-display ${direction}`;

    // Set card border color
    card.className = `prediction-card prediction-${direction}`;

    // Confidence percentage
    confidenceEl.textContent = `${predictionData.confidence}%`;
    confidenceEl.style.color = isUp ? 'var(--up-color)' : 'var(--down-color)';

    // Model accuracy
    accuracyEl.textContent = `${predictionData.model_accuracy}%`;

    // Animated confidence bar
    barEl.className = `confidence-bar-fill ${direction}`;
    setTimeout(() => {
        barEl.style.width = `${predictionData.confidence}%`;
    }, 300); // delay for animation effect
}


// ══════════════════════════════════════════════════════════
// 3. UPDATE METRICS BAR (top indicator values)
// ══════════════════════════════════════════════════════════
function updateMetricsBar() {
    if (!predictionData) return;

    const ind = predictionData.indicators;

    // Last close price
    const priceEl = document.getElementById('metric-price-value');
    priceEl.textContent = `$${predictionData.last_close.toLocaleString('en-US', { minimumFractionDigits: 2 })}`;

    // Price change percentage
    const changeEl = document.getElementById('metric-change-value');
    const changePct = ind.price_change_pct;
    const changeSign = changePct >= 0 ? '+' : '';
    changeEl.textContent = `${changeSign}${changePct.toFixed(2)}%`;
    changeEl.className = `metric-value ${changePct >= 0 ? 'up' : 'down'}`;

    // SMA values
    document.getElementById('metric-sma5-value').textContent =
        `$${ind.sma_5.toLocaleString('en-US', { minimumFractionDigits: 2 })}`;
    document.getElementById('metric-sma20-value').textContent =
        `$${ind.sma_20.toLocaleString('en-US', { minimumFractionDigits: 2 })}`;

    // EMA values
    document.getElementById('metric-ema5-value').textContent =
        `$${ind.ema_5.toLocaleString('en-US', { minimumFractionDigits: 2 })}`;
    document.getElementById('metric-ema20-value').textContent =
        `$${ind.ema_20.toLocaleString('en-US', { minimumFractionDigits: 2 })}`;

    // Volatility
    document.getElementById('metric-volatility-value').textContent =
        `${ind.volatility.toFixed(2)}%`;
}


// ══════════════════════════════════════════════════════════
// 4. UPDATE LAST UPDATED TIMESTAMP
// ══════════════════════════════════════════════════════════
function updateLastUpdated() {
    if (!predictionData) return;
    const el = document.getElementById('last-updated');
    el.textContent = `Updated: ${predictionData.generated_at}`;
}


// ══════════════════════════════════════════════════════════
// 5. RENDER PRICE CHART (Candlestick or Line)
// ══════════════════════════════════════════════════════════
function renderChart() {
    if (!predictionData || !predictionData.chart_data) return;

    const cd = predictionData.chart_data;
    const traces = [];

    if (currentChartType === 'candlestick') {
        // ── Candlestick trace ──
        traces.push({
            x: cd.dates,
            open: cd.open,
            high: cd.high,
            low: cd.low,
            close: cd.close,
            type: 'candlestick',
            name: 'Gold Price',
            increasing: { line: { color: '#10b981' }, fillcolor: '#10b981' },
            decreasing: { line: { color: '#ef4444' }, fillcolor: '#ef4444' },
        });
    } else {
        // ── Line trace ──
        traces.push({
            x: cd.dates,
            y: cd.close,
            type: 'scatter',
            mode: 'lines',
            name: 'Close Price',
            line: { color: '#3b82f6', width: 2 },
            fill: 'tozeroy',
            fillcolor: 'rgba(59, 130, 246, 0.05)',
        });
    }

    // ── SMA(5) overlay ──
    traces.push({
        x: cd.dates,
        y: cd.sma_5,
        type: 'scatter',
        mode: 'lines',
        name: 'SMA(5)',
        line: { color: '#f59e0b', width: 1.2, dash: 'dot' },
    });

    // ── SMA(20) overlay ──
    traces.push({
        x: cd.dates,
        y: cd.sma_20,
        type: 'scatter',
        mode: 'lines',
        name: 'SMA(20)',
        line: { color: '#8b5cf6', width: 1.2, dash: 'dot' },
    });

    // ── EMA(5) overlay ──
    traces.push({
        x: cd.dates,
        y: cd.ema_5,
        type: 'scatter',
        mode: 'lines',
        name: 'EMA(5)',
        line: { color: '#06b6d4', width: 1, dash: 'dash' },
    });

    // ── EMA(20) overlay ──
    traces.push({
        x: cd.dates,
        y: cd.ema_20,
        type: 'scatter',
        mode: 'lines',
        name: 'EMA(20)',
        line: { color: '#ec4899', width: 1, dash: 'dash' },
    });

    // ── Chart layout ──
    const layout = {
        paper_bgcolor: 'rgba(0,0,0,0)',
        plot_bgcolor: 'rgba(0,0,0,0)',
        font: { color: '#8899aa', family: 'Inter, sans-serif', size: 11 },
        xaxis: {
            gridcolor: 'rgba(30,42,58,0.6)',
            rangeslider: { visible: false },
            type: 'date',
        },
        yaxis: {
            gridcolor: 'rgba(30,42,58,0.6)',
            title: { text: 'Price (USD)', standoff: 10 },
            tickprefix: '$',
            side: 'right',
        },
        legend: {
            orientation: 'h',
            x: 0,
            y: 1.12,
            font: { size: 10, color: '#8899aa' },
        },
        margin: { t: 35, r: 60, b: 40, l: 20 },
        autosize: true,
        hovermode: 'x unified',
        dragmode: 'zoom',
    };

    const config = {
        responsive: true,
        displayModeBar: true,
        modeBarButtonsToRemove: ['lasso2d', 'select2d'],
        displaylogo: false,
    };

    Plotly.newPlot('price-chart', traces, layout, config);
}


// ══════════════════════════════════════════════════════════
// 6. CHART TYPE TOGGLE (Candlestick ↔ Line)
// ══════════════════════════════════════════════════════════
function setupChartToggle() {
    const buttons = document.querySelectorAll('.chart-btn');
    buttons.forEach(btn => {
        btn.addEventListener('click', () => {
            // Update active state
            buttons.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');

            // Update chart type and re-render
            currentChartType = btn.dataset.type;
            renderChart();
        });
    });
}


// ══════════════════════════════════════════════════════════
// 7. EMOTION SELECTION BUTTONS
// ══════════════════════════════════════════════════════════
function setupEmotionButtons() {
    const buttons = document.querySelectorAll('.emotion-btn');
    const saveBtn = document.getElementById('save-emotion-btn');

    buttons.forEach(btn => {
        btn.addEventListener('click', () => {
            // Deselect all
            buttons.forEach(b => b.classList.remove('selected'));

            // Select this one
            btn.classList.add('selected');
            selectedEmotion = btn.dataset.emotion;

            // Enable save button
            saveBtn.disabled = false;
        });
    });
}


// ══════════════════════════════════════════════════════════
// 8. SAVE EMOTION ENTRY
// ══════════════════════════════════════════════════════════
function setupSaveButton() {
    const saveBtn = document.getElementById('save-emotion-btn');

    saveBtn.addEventListener('click', () => {
        if (!selectedEmotion) return;

        const notes = document.getElementById('trade-notes').value.trim();
        const timestamp = new Date().toISOString().slice(0, 19).replace('T', ' ');

        // Create the entry
        const entry = {
            timestamp: timestamp,
            emotion: selectedEmotion,
            notes: notes || '',
        };

        // Load existing entries from localStorage
        let entries = JSON.parse(localStorage.getItem(EMOTION_STORAGE_KEY) || '[]');
        entries.push(entry);
        localStorage.setItem(EMOTION_STORAGE_KEY, JSON.stringify(entries));

        console.log('✅ Emotion entry saved:', entry);

        // Visual feedback
        saveBtn.textContent = '✓ Saved!';
        saveBtn.classList.add('saved');
        setTimeout(() => {
            saveBtn.textContent = 'Save Entry';
            saveBtn.classList.remove('saved');
        }, 2000);

        // Reset form
        selectedEmotion = null;
        document.querySelectorAll('.emotion-btn').forEach(b => b.classList.remove('selected'));
        document.getElementById('trade-notes').value = '';
        saveBtn.disabled = true;

        // Refresh summary table
        loadAndDisplayEmotionSummary();

        // Show toast notification
        showToast('Emotion entry recorded successfully');
    });
}


// ══════════════════════════════════════════════════════════
// 9. LOAD & DISPLAY EMOTION SUMMARY TABLE
// ══════════════════════════════════════════════════════════
function loadAndDisplayEmotionSummary() {
    // Merge CSV data + localStorage entries
    const localEntries = JSON.parse(localStorage.getItem(EMOTION_STORAGE_KEY) || '[]');

    // Load entries from emotion_log.csv as well (initial seed data)
    fetch('data/emotion_log.csv')
        .then(response => {
            if (!response.ok) throw new Error('CSV not found');
            return response.text();
        })
        .then(csvText => {
            const csvEntries = parseEmotionCSV(csvText);
            const allEntries = [...csvEntries, ...localEntries];
            renderEmotionSummary(allEntries);
        })
        .catch(() => {
            // If CSV fails, just use localStorage entries
            renderEmotionSummary(localEntries);
        });
}


/**
 * Parse emotion_log.csv into array of entry objects.
 * Format: timestamp,emotion,notes
 */
function parseEmotionCSV(csvText) {
    const lines = csvText.trim().split('\n');
    if (lines.length < 2) return []; // header only

    return lines.slice(1).map(line => {
        const parts = line.split(',');
        return {
            timestamp: parts[0] || '',
            emotion: parts[1] || '',
            notes: parts.slice(2).join(',') || '',
        };
    }).filter(e => e.emotion);
}


/**
 * Render emotion counts and distribution bars into the summary table.
 */
function renderEmotionSummary(entries) {
    const tbody = document.getElementById('emotion-summary-body');
    const totalEl = document.getElementById('total-entries');
    const total = entries.length;

    // Count by emotion
    const counts = { Confident: 0, Neutral: 0, Fearful: 0 };
    entries.forEach(e => {
        const key = e.emotion.charAt(0).toUpperCase() + e.emotion.slice(1).toLowerCase();
        if (counts.hasOwnProperty(key)) {
            counts[key]++;
        }
    });

    // Build table rows
    const emotions = [
        { name: 'Confident', cssClass: 'confident', emoji: '😎' },
        { name: 'Neutral',   cssClass: 'neutral',   emoji: '😐' },
        { name: 'Fearful',   cssClass: 'fearful',   emoji: '😰' },
    ];

    tbody.innerHTML = emotions.map(emo => {
        const count = counts[emo.name] || 0;
        const pct = total > 0 ? (count / total * 100) : 0;

        return `
            <tr>
                <td>
                    <span class="emotion-indicator">
                        <span class="emotion-dot ${emo.cssClass}"></span>
                        ${emo.emoji} ${emo.name}
                    </span>
                </td>
                <td>${count}</td>
                <td>
                    <div class="distribution-bar">
                        <div class="distribution-fill ${emo.cssClass}" style="width: ${pct}%"></div>
                    </div>
                </td>
            </tr>
        `;
    }).join('');

    totalEl.textContent = `Total entries: ${total}`;
}


// ══════════════════════════════════════════════════════════
// 10. TOAST NOTIFICATION
// ══════════════════════════════════════════════════════════
function showToast(message) {
    // Remove any existing toast
    const existing = document.querySelector('.toast');
    if (existing) existing.remove();

    const toast = document.createElement('div');
    toast.className = 'toast';
    toast.textContent = message;
    document.body.appendChild(toast);

    // Auto-remove after 3 seconds
    setTimeout(() => {
        toast.classList.add('leaving');
        setTimeout(() => toast.remove(), 300);
    }, 3000);
}
